services:
  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: electrolernapp2020
      MYSQL_DATABASE: db_electrolernapp
      MYSQL_USER: electrolernapp
      MYSQL_PASSWORD: electrolernapp2020
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080