version: "3.8"
services:
  mariadb:
    image: mariadb:10
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: electrolernapp2020
      MYSQL_DATABASE: db_electrolernapp
      MYSQL_USER: electrolernapp
      MYSQL_PASSWORD: electrolernapp2020
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    ports:
      - 7777:8080

volumes:
  db_data: